# Generated by Django 3.2 on 2021-06-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0002_regisration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regisration',
            old_name='alergies',
            new_name='allergies',
        ),
    ]
