# Generated by Django 3.2 on 2021-07-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0003_rename_alergies_regisration_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='regisration',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
